name: "Build & Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 0.1.1)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
      BRANCH: master   # change to main if needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          scope: "@evotecit"

      - name: Install terser
        run: npm i -D terser

      - name: Build dist
        run: |
          set -e
          mkdir -p dist
          npx terser \
            sources/datatables/columnHighlighter/datatables.columnHighlighter.js \
            --compress --mangle \
            --comments=/^!/ \
            -o dist/datatables.columnHighlighter.min.js
          cp sources/datatables/columnHighlighter/datatables.columnHighlighter.js dist/

      - name: Bump package.json version (if present)
        run: |
          if [ -f package.json ]; then
            node -e "let f='package.json',p=require('./'+f);p.version=process.env.VERSION;require('fs').writeFileSync(f, JSON.stringify(p,null,2)+'\n')"
          fi

      - name: Commit dist (and package.json if changed)
        run: |
          git config user.name  "evotec-bot"
          git config user.email "actions@users.noreply.github.com"
          git add dist/ package.json 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(release): dist for v$VERSION"
            git push origin HEAD:$BRANCH
          fi

      - name: Create tag (skip if exists)
        run: |
          TAG="v$VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG exists; skipping."
          else
            git tag -a "$TAG" -m "HTMLExtensions $TAG"
            git push origin "$TAG"
          fi

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          files: |
            dist/datatables.columnHighlighter.min.js
            dist/datatables.columnHighlighter.js

      - name: Publish to npm (only if token present)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -n "$NODE_AUTH_TOKEN" ]; then
            if [ -f package.json ]; then
              npm publish --access public || echo "npm publish failed; continuing."
            else
              echo "package.json missing; skipping npm publish."
            fi
          else
            echo "NPM_TOKEN not set — skipping npm publish."
          fi
